// Blueprint: walking down a street drawn as an architect's perspective study
// on a cyanotype sheet. One-point perspective: facades with their floor lines
// running to the vanishing point, window bays, lamp posts, the kerbs and the
// road's centre line, the horizon, and the construction lines a draughtsman
// leaves in. The camera walks forward, so the drawing is always being
// re-projected.
//
// The medium: Rough.js's two big dials, roughness and bowing, run the whole
// range from a ruled technical drawing to a hurried sketch. This piece hands
// that dial to the music. In the calm the draughtsman is precise (roughness
// ~0.35, no boil, ruled lines that still overshoot their corners the way ink
// does); in the drop the hand loosens to a fast pencil scrawl, lines bow and
// double, and the drawing boils eight times a second.
//
// Each facade is generated by Rough.js flat, in its own plane (metres times
// ten, so the library's wobble is about 20 cm on the building), cached, and
// every frame its op points are pushed through the perspective projection.
// So the hand-drawn wobble belongs to the building and recedes with it, and
// Rough.js is asked again only when the seed boils or the hand changes.
//
// Music, each in its own place:
//   kick   one facade ahead is hatched in (a hachure fill in its own plane,
//          so the hatching recedes with the wall), then fades
//   clap   a revision cloud, the architect's redline, is scalloped round a
//          block of windows with its delta tag
//   hats   single windows are filled in, one at a time
//   bass   the pencil presses harder
//   drop   the hand loosens (roughness, bowing, boil), the construction
//          lines come in through every corner, the walk speeds up

(function () {
  'use strict';

  // Rough.js 4.6.6 (MIT, Preet Shihn), the IIFE build, which sets window.rough.
  const ROUGH_URL = 'https://cdn.jsdelivr.net/npm/roughjs@4.6.6/bundled/rough.js';
  function loadRough() {
    if (window.rough) return Promise.resolve(window.rough);
    if (!window.__vizRoughLoad) {
      window.__vizRoughLoad = new Promise((resolve, reject) => {
        const s = document.createElement('script');
        s.src = ROUGH_URL;
        s.async = true;
        s.onload = () => (window.rough ? resolve(window.rough) : reject(new Error('rough.js loaded without a global')));
        s.onerror = () => { window.__vizRoughLoad = null; reject(new Error('could not load ' + ROUGH_URL)); };
        document.head.appendChild(s);
      });
    }
    return window.__vizRoughLoad;
  }

  const BEAT = 60 / 124;
  const TAU = Math.PI * 2;
  const clamp = (x, a, b) => (x < a ? a : x > b ? b : x);
  const clamp01 = (x) => clamp(x, 0, 1);
  const lerp = (a, b, u) => a + (b - a) * u;
  const ease = (cur, target, rate, dt) => cur + (target - cur) * (1 - Math.exp(-rate * dt));
  function mulberry(seed) {
    let a = seed >>> 0;
    return function () {
      a = (a + 0x6D2B79F5) >>> 0;
      let t = a;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  const seedOf = (a, b, c) => ((Math.imul(a | 0, 73856093) ^ Math.imul(b | 0, 19349663) ^ Math.imul(c | 0, 83492791)) >>> 1) % 2147483000 + 1;

  // Push a drawable's ops through a point mapping into a Path2D. kinds is a
  // bit mask: 1 outline, 2 solid fill, 4 fill sketch.
  const TMP = [0, 0], TMP2 = [0, 0], TMP3 = [0, 0];
  function trace(path, d, map, kinds) {
    for (const s of d.sets) {
      const k = s.type === 'fillSketch' ? 4 : s.type === 'fillPath' ? 2 : 1;
      if (!(k & kinds)) continue;
      for (const o of s.ops) {
        const a = o.data;
        if (o.op === 'move') { map(a[0], a[1], TMP); path.moveTo(TMP[0], TMP[1]); }
        else if (o.op === 'bcurveTo') {
          map(a[0], a[1], TMP); map(a[2], a[3], TMP2); map(a[4], a[5], TMP3);
          path.bezierCurveTo(TMP[0], TMP[1], TMP2[0], TMP2[1], TMP3[0], TMP3[1]);
        } else { map(a[0], a[1], TMP); path.lineTo(TMP[0], TMP[1]); }
      }
    }
  }
  const ident = (x, y, out) => { out[0] = x; out[1] = y; };

  const PAPERS = [
    { name: 'Cyanotype', ground: '#1D4A88', blot: '#163B70', line: '#EAF0F7', faint: '#A9C0E0', red: '#F3BE6A', fill: '#2A5A99' },
    { name: 'Whiteprint', ground: '#ECEAE2', blot: '#DAD9D6', line: '#34438F', faint: '#8C95C2', red: '#CF4430', fill: '#E4E3E0' },
    { name: 'Pencil on vellum', ground: '#E4E1D6', blot: '#D3D0C4', line: '#2D2D31', faint: '#8F8D88', red: '#BF3A2B', fill: '#DEDBD0' },
  ];

  const PRESETS = {
    calm: { hand: 0.35, bow: 0.6, walk: 0.5, boil: 0, guides: 0.15 },
    drop: { hand: 2.1, bow: 3.5, walk: 1.4, boil: 8, guides: 1 },
    // A slow, loose charcoal-ish study, no boil.
    study: { hand: 1.4, bow: 5, walk: 0.3, boil: 0, guides: 0.6, follow: 0 },
  };
  const DRIVE = ['hand', 'bow', 'walk', 'boil', 'guides'];

  const S = 10;                 // local drawing units per metre
  const EYE = 1.6;              // eye height, metres
  const NEAR = 1.5;             // near plane, metres: points nearer are pinned to it
  const FAR = 150;
  const KERB = 6, WALK = 9;     // road half width, pavement edge
  const FLOOR = 3.4, BAY = 3.2;
  const PER_FRAME = 10;         // facades regenerated per frame at most

  VIZ.register({
    id: 'rough3',
    name: 'Blueprint',
    order: 1103,

    params: [
      { key: 'hand', label: 'Ruled / scrawled (roughness)', type: 'range', min: 0.1, max: 3.5, default: PRESETS.calm.hand, step: 0.01 },
      { key: 'bow', label: 'Bowing', type: 'range', min: 0, max: 8, default: PRESETS.calm.bow, step: 0.01 },
      { key: 'walk', label: 'Walking speed', type: 'range', min: 0, max: 2.5, default: PRESETS.calm.walk, step: 0.01 },
      { key: 'boil', label: 'Boil (redraws a second)', type: 'range', min: 0, max: 12, default: PRESETS.calm.boil, step: 0.1 },
      { key: 'guides', label: 'Construction lines', type: 'range', min: 0, max: 1, default: PRESETS.calm.guides, step: 0.01 },
      { key: 'paper', label: 'Sheet', type: 'select', options: PAPERS.map((q) => q.name), default: 0 },
      { key: 'react', label: 'Kick hatching', type: 'range', min: 0, max: 1, default: 1, step: 0.01 },
      { key: 'follow', label: 'Follow the track', type: 'select', options: ['Off', 'On'], default: 1 },
    ],
    presets: PRESETS,

    gallery: {
      title: 'Blueprint',
      technique: 'Rough.js 4.6.6 (loaded from jsDelivr) through its generator. Each facade and front face is generated flat in its own plane (at ten units a metre, so the wobble is building-sized), cached, and each frame its bezier ops are mapped through a one-point perspective projection into one Path2D per ink; hidden lines are knocked out by painting the projected faces far to near. Roughness and bowing (quantised, regenerated a few facades per frame) and the seed (the boil) are the performance controls. Kick hatching is a hachure fill in the facade\'s plane; revision clouds are rough.path from SVG arc commands; the title block, border and lettering sit on the sheet in screen space.',
      brief: 'A walk down a street drawn as an architect\'s one-point perspective study, on a cyanotype sheet with its title block. In the calm the draughtsman is precise: ruled lines, overshooting corners, a still drawing. On the drop the hand loosens into a pencil scrawl: roughness and bowing climb, every line boils, construction lines shoot out of the vanishing point through every corner, and the walk speeds up. Each kick hatches one facade ahead in its own perspective; each clap draws a redline revision cloud round a block of windows, with its delta tag; hats fill single windows; the bass presses the pencil harder.',
      lineage: [
        'Batch 08 (2026-09-29), Rough.js sketch 3 of 5: roughness and bowing as the performance.',
        'Architects\' perspective sketches and construction drawings, blueprints (cyanotype) and diazo whiteprints, the revision cloud and delta of drawing markup.',
        'Kin to the one-point perspective walks of Laser Congregation and Night Train in viz.',
      ],
    },

    preload(p) {
      const hold = !!window.HARNESS && typeof p._incrementPreload === 'function';
      if (hold) p._incrementPreload();
      loadRough().catch((e) => console.warn('rough3: ' + e.message)).then(() => { if (hold) p._decrementPreload(); });
    },

    setup() {},
    enter() { loadRough().catch(() => {}); this.reset(); },

    reset() {
      this.lastMs = null;
      this.clock = 0;
      this.env = { kf: 0, ks: 0, kArm: true, cf: 0, cs: 0, cArm: true, hf: 0, hs: 0, hArm: true,
        bass: 0, low: 0, dropOn: false, auto: 0, lastK: -9, lastC: -9, lastH: -9 };
      this.cam = 0;
      this.camX = 0;
      this.seq = 0;
      this.blocks = [];
      this.nextZ = [4, 7];      // next free z on each side
      this.rev = 0;
      this.texture = null;
      this.sheet = null;
    },

    listen(sg, dt, T) {
      const e = this.env;
      const k = sg[0] / 100;
      e.kf = ease(e.kf, k, 40, dt);
      e.ks = ease(e.ks, k, 3, dt);
      const kOn = clamp01((e.kf - e.ks) * 2.2);
      let kick = 0;
      if (e.kArm && kOn > 0.2 && T - e.lastK > 0.22) { kick = kOn; e.kArm = false; e.lastK = T; }
      if (kOn < 0.1) e.kArm = true;
      const cl = (sg[3] + sg[4] + sg[5]) / 300;
      e.cf = ease(e.cf, cl, 30, dt);
      e.cs = ease(e.cs, cl, 2.5, dt);
      const cOn = clamp01((e.cf - e.cs) * 3);
      let clap = 0;
      if (e.cArm && cOn > 0.25 && T - e.lastC > 0.3) { clap = cOn; e.cArm = false; e.lastC = T; }
      if (cOn < 0.1) e.cArm = true;
      const hh = (sg[7] + sg[8]) / 200;
      e.hf = ease(e.hf, hh, 45, dt);
      e.hs = ease(e.hs, hh, 4, dt);
      const hOn = clamp01((e.hf - e.hs) * 3);
      let hat = 0;
      if (e.hArm && hOn > 0.12 && T - e.lastH > 0.07) { hat = 1; e.hArm = false; e.lastH = T; }
      if (hOn < 0.05) e.hArm = true;
      e.bass = ease(e.bass, (sg[0] + sg[1] + sg[2]) / 300, 3, dt);
      e.low = ease(e.low, sg[1], 1.2, dt);
      if (!e.dropOn && e.low > 27) e.dropOn = true;
      else if (e.dropOn && e.low < 19) e.dropOn = false;
      return { kick, clap, hat };
    },

    // A building: street facade in the plane x = side * xs, z0..z1, height h;
    // front face at z0 from xs outwards by thick.
    spawn(side) {
      const id = ++this.seq;
      const rng = mulberry(seedOf(id, side + 5, 1));
      const z0 = this.nextZ[side > 0 ? 1 : 0];
      const bays = 3 + Math.floor(rng() * 5);
      const len = bays * BAY + 0.6;
      const floors = 2 + Math.floor(rng() * rng() * 7);
      const b = { id, side, z0, z1: z0 + len, bays, floors, h: floors * FLOOR + 0.8 + rng() * 0.8,
        xs: WALK + (rng() < 0.3 ? 1.5 * rng() : 0), thick: 10 + rng() * 8, key: null, drw: null,
        hatchT: -9, hatchA: 0, lit: [], revs: [], lamp: rng() < 0.7, cornice: rng() < 0.5 };
      // Gaps between buildings (side streets) now and then.
      this.nextZ[side > 0 ? 1 : 0] = b.z1 + (rng() < 0.25 ? 5 + rng() * 6 : 0.3);
      this.blocks.push(b);
      return b;
    },

    // Generate a building's drawings flat in their own planes. Local facade
    // coordinates: u along the street (z - z0), v up; front face: u outwards
    // from the facade, v up. Both in metres * S.
    build(gen, b, hand, bow, boil) {
      const L = (b.z1 - b.z0) * S, Hh = b.h * S, Tk = b.thick * S;
      const o = (n) => ({ roughness: hand, bowing: bow, seed: seedOf(b.id, n, boil) });
      const facade = [], front = [];
      facade.push(gen.rectangle(0, 0, L, Hh, o(1)));
      for (let f = 1; f <= b.floors; f++) facade.push(gen.line(0, f * FLOOR * S - 4, L, f * FLOOR * S - 4, o(10 + f)));
      for (let k = 1; k < b.bays; k++) facade.push(gen.line(k * BAY * S, 0, k * BAY * S, b.floors * FLOOR * S - 4, o(30 + k)));
      if (b.cornice) facade.push(gen.line(-4, Hh - 5, L + 4, Hh - 5, o(60)));
      // Window openings inside each cell, as small rectangles.
      for (let f = 0; f < b.floors; f++) {
        for (let k = 0; k < b.bays; k++) {
          const x = k * BAY * S + 8, y = f * FLOOR * S + (f === 0 ? 4 : 9);
          facade.push(gen.rectangle(x, y, BAY * S - 16, FLOOR * S - (f === 0 ? 12 : 20), o(100 + f * 20 + k)));
        }
      }
      front.push(gen.rectangle(0, 0, Tk, Hh, o(2)));
      for (let f = 1; f <= b.floors; f++) front.push(gen.line(0, f * FLOOR * S - 4, Tk, f * FLOOR * S - 4, o(300 + f)));
      const nb = Math.max(1, Math.floor(b.thick / BAY));
      for (let f = 0; f < b.floors; f++) {
        for (let k = 0; k < nb; k++) {
          const w = Tk / nb;
          front.push(gen.rectangle(k * w + 7, f * FLOOR * S + 9, w - 14, FLOOR * S - 20, o(400 + f * 20 + k)));
        }
      }
      b.drw = { facade, front };
      b.hatch = null;
      for (const r of b.revs) r.d = null;
      for (const w of b.lit) w.d = null;
    },

    draw(p, signals, params, ctx) {
      p.colorMode(p.RGB, 255);
      if (this.clock === undefined) this.reset();
      const ms = p.millis();
      const dt = this.lastMs === null ? 1 / 60 : clamp((ms - this.lastMs) / 1000, 0, 0.1);
      this.lastMs = ms;
      this.clock += dt;
      const T = this.clock;
      const e = this.env;
      const hit = this.listen(signals, dt, T);
      const W = ctx.width, H = ctx.height;
      const g = p.drawingContext;
      const pal = PAPERS[clamp(Math.round(params.paper), 0, PAPERS.length - 1)];

      const follow = Math.round(params.follow) === 1;
      e.auto = ease(e.auto, follow && e.dropOn ? 1 : 0, e.dropOn ? 1.3 : 0.45, dt);
      const P = {};
      for (const k of DRIVE) P[k] = params[k] + (PRESETS.drop[k] - params[k]) * (follow ? e.auto : 0);

      p.background(pal.ground);
      this.paperTexture(g, W, H, pal);
      const R = window.rough;
      if (!R) return;
      if (!this.gen) this.gen = R.generator();
      const gen = this.gen;

      // ---- walk
      this.cam += (1.2 + 5.5 * P.walk) * dt;
      this.camX = 0.9 * Math.sin(T * 0.13) + 0.4 * Math.sin(T * 0.31);
      const cam = this.cam, camX = this.camX;
      for (const side of [-1, 1]) {
        while (this.nextZ[side > 0 ? 1 : 0] < cam + FAR) this.spawn(side);
      }
      this.blocks = this.blocks.filter((b) => b.z1 > cam + 0.2);

      const F = H * 0.95;
      const hy = H * 0.56;
      const vx = W / 2 - F * camX / 1e6;          // vanishing point
      // Points nearer than NEAR are pinned to it rather than clipped. Nearer
      // than that the pinned points run to thousands of units, and a bezier
      // with control points out there made Chromium drop the whole ground
      // path (seen at high roughness x bowing, 2026-09-29).
      const proj = (X, Y, Z, out) => {
        const z = Math.max(NEAR, Z - cam);
        out[0] = W / 2 + F * (X - camX) / z;
        out[1] = hy - F * (Y - EYE) / z;
      };

      // ---- the hand: quantised so a glide re-generates in steps, and
      // re-generated a few buildings per frame.
      const handQ = Math.round(P.hand * 10) / 10;
      const bowQ = Math.round(P.bow * 4) / 4;
      const boil = P.boil > 0.2 ? Math.floor(T * P.boil) : 0;
      const key = handQ + '|' + bowQ + '|' + boil;
      let budget = PER_FRAME;
      const ordered = this.blocks.slice().sort((a, b) => a.z0 - b.z0);
      for (const b of ordered) {
        if (b.key === key) continue;
        if (b.drw && budget <= 0) continue;
        this.build(gen, b, handQ, bowQ, boil);
        b.key = key;
        budget--;
      }

      // ---- events
      if (hit.kick && params.react > 0) {
        const cands = this.blocks.filter((b) => b.z0 - cam > 8 && b.z0 - cam < 45 && T - b.hatchT > 2);
        if (cands.length) {
          const b = cands[Math.floor((T * 7.31) % 1 * cands.length)];
          b.hatchT = T; b.hatchA = clamp01(0.5 + hit.kick) * params.react;
          b.hatchAng = (b.id % 2 ? 45 : -45) + (b.id % 3) * 10;
        }
      }
      if (hit.clap) {
        const cands = this.blocks.filter((b) => b.z0 - cam > 5 && b.z0 - cam < 40 && b.floors >= 2 && b.bays >= 3);
        if (cands.length) {
          const b = cands[Math.floor((T * 3.17) % 1 * cands.length)];
          const rng = mulberry(seedOf(b.id, T * 60, 4));
          const k0 = Math.floor(rng() * (b.bays - 1)), f0 = Math.floor(rng() * (b.floors - 1));
          const nk = 1 + Math.floor(rng() * Math.min(3, b.bays - k0)), nf = 1 + Math.floor(rng() * Math.min(2, b.floors - f0));
          // At most three clouds on the sheet: the oldest is rubbed out.
          const live = this.blocks.filter((q) => q.revs.some((r) => T - r.t < 6));
          if (live.length >= 3) { const old = live.reduce((a, q) => (q.revs[0].t < a.revs[0].t ? q : a)); old.revs.shift(); }
          b.revs.push({ k0, f0, nk, nf, t: T, n: ++this.rev, d: null });
          if (b.revs.length > 1) b.revs.shift();
        }
      }
      if (hit.hat) {
        const cands = this.blocks.filter((b) => b.z0 - cam > 3 && b.z0 - cam < 60);
        if (cands.length) {
          const b = cands[Math.floor((T * 11.7) % 1 * cands.length)];
          const r = (T * 97.3) % 1;
          b.lit.push({ k: Math.floor(r * b.bays), f: Math.floor(((T * 53.1) % 1) * b.floors), t: T, d: null });
          if (b.lit.length > 6) b.lit.shift();
        }
      }

      const press = 1 + 0.9 * e.bass;
      const lw = 1.25 * press;
      g.save();
      g.lineCap = 'round';
      g.lineJoin = 'round';
      g.globalCompositeOperation = 'source-over';
      g.globalAlpha = 1;
      g.setLineDash([]);

      // ---- ground: horizon, kerbs, pavement edges, centre line. Drawn
      // flat in the ground plane (x, z) in local units, then projected.
      if (!this.ground || this.ground.key !== key) {
        const o = (n) => ({ roughness: handQ, bowing: bowQ, seed: seedOf(7, n, boil) });
        // Long lines are drawn in 15 m strokes, as a draughtsman would: one
        // Rough line 150 m long bows by metres at a high bowing.
        const segs = [];
        for (let k = 0; k < 40; k++) segs.push(gen.line(0, 0, 15 * S + 3, 0, o(200 + k)));
        const dashes = [];
        for (let k = 0; k < 40; k++) dashes.push(gen.line(0, 0, 3 * S, 0, o(100 + k)));
        const horizon = [];
        for (let k = 0; k < 4; k++) horizon.push(gen.line(-40 + k * (W + 80) / 4, hy, -40 + (k + 1) * (W + 80) / 4 + 4, hy, o(3 + k)));
        this.ground = { key, segs, dashes, horizon };
      }
      const G = this.ground;
      // The horizon is behind everything; the ground (all of it nearer the
      // middle of the street than the facades) is never hidden by a
      // building, so it is inked after them.
      const hp = new Path2D();
      for (const d of G.horizon) trace(hp, d, ident, 1);
      g.strokeStyle = pal.line;
      g.globalAlpha = 0.8;
      g.lineWidth = lw * 0.9;
      g.stroke(hp);
      const gp = new Path2D();
      const s0 = Math.floor((cam + NEAR) / 15);
      for (let k = 0; k < 10; k++) {
        const z = (s0 + k) * 15;
        let n = 0;
        for (const X of [-WALK, -KERB, KERB, WALK]) {
          // Local u runs along the street, the wobble (local v) across it.
          const d = G.segs[(((s0 + k) * 4 + n++) % 40 + 40) % 40];
          trace(gp, d, (u, v, out) => proj(X + v / S, 0, z + u / S, out), 1);
        }
      }
      // Centre dashes: every 9 m, anchored to the road, not the camera.
      const d0 = Math.ceil((cam + NEAR) / 9);
      for (let k = 0; k < 16; k++) {
        const z = (d0 + k) * 9;
        const d = G.dashes[((d0 + k) % 40 + 40) % 40];
        trace(gp, d, (u, v, out) => proj(v / S, 0, z + u / S, out), 1);
      }
      // Paving joints across both pavements every 3 m: the ground's own
      // rhythm, so the walk's speed reads.
      const j0 = Math.ceil((cam + NEAR) / 3);
      for (let k = 0; k < 30; k++) {
        const z = (j0 + k) * 3;
        const d = G.dashes[((j0 + k) * 7 % 40 + 40) % 40];
        for (const side of [-1, 1]) trace(gp, d, (u, v, out) => proj(side * (KERB + u / S), 0, z + v / S, out), 1);
      }

      // ---- construction lines from the vanishing point to the sheet's
      // corners, and in the drop through every building corner.
      const guides = P.guides;
      if (guides > 0.01) {
        const cp = new Path2D();
        const ext = (x, y) => {
          const dx = x - vx, dy = y - hy, L = Math.hypot(dx, dy) || 1;
          const far = Math.max(W, H) * 1.5;
          cp.moveTo(vx - dx / L * 20, hy - dy / L * 20);
          cp.lineTo(vx + dx / L * far, hy + dy / L * far);
        };
        ext(0, 0); ext(W, 0); ext(0, H); ext(W, H);
        if (guides > 0.3) {
          for (const b of this.blocks) {
            if (b.z0 - cam > 70 || b.z0 - cam < 2) continue;
            proj(b.side * b.xs, b.h, b.z0, TMP); ext(TMP[0], TMP[1]);
            proj(b.side * (b.xs + b.thick), b.h, b.z0, TMP); ext(TMP[0], TMP[1]);
          }
        }
        g.strokeStyle = pal.faint;
        g.lineWidth = 0.6;
        g.globalAlpha = 0.18 + 0.3 * guides;
        g.stroke(cp);
        // Measuring ticks along the horizon.
        g.globalAlpha = 0.5 * guides;
        g.beginPath();
        for (let x = vx % 40; x < W; x += 40) { g.moveTo(x, hy - 4); g.lineTo(x, hy + 4); }
        g.stroke();
      }

      // ---- buildings, far to near, each face knocked out then inked
      ordered.reverse();
      for (const b of ordered) {
        if (!b.drw || b.z0 - cam > FAR) continue;
        const side = b.side;
        const fxz = (u, v, out) => proj(side * b.xs, v / S, b.z0 + u / S, out);
        const frt = (u, v, out) => proj(side * (b.xs + u / S), v / S, b.z0, out);
        const fade = clamp01((FAR - (b.z0 - cam)) / 40);
        const face = new Path2D();
        const q = (X, Y, Z) => { proj(X, Y, Z, TMP); return [TMP[0], TMP[1]]; };
        let a = q(side * b.xs, 0, b.z0), c = q(side * b.xs, 0, b.z1), d = q(side * b.xs, b.h, b.z1), f = q(side * b.xs, b.h, b.z0);
        face.moveTo(a[0], a[1]); face.lineTo(c[0], c[1]); face.lineTo(d[0], d[1]); face.lineTo(f[0], f[1]); face.closePath();
        const frontVis = b.z0 - cam > NEAR;
        if (frontVis) {
          const f2 = q(side * (b.xs + b.thick), b.h, b.z0), a2 = q(side * (b.xs + b.thick), 0, b.z0);
          face.moveTo(a[0], a[1]); face.lineTo(a2[0], a2[1]); face.lineTo(f2[0], f2[1]); face.lineTo(f[0], f[1]); face.closePath();
        }
        g.globalAlpha = 1;
        g.fillStyle = pal.ground;
        g.fill(face, 'nonzero');
        g.globalAlpha = 0.55 * fade;
        g.fillStyle = pal.fill;
        g.fill(face, 'nonzero');

        // Lit windows (hats): solid fills in the facade plane.
        for (const w of b.lit) {
          const age = T - w.t;
          if (age > 4) continue;
          if (!w.d) w.d = this.gen.rectangle(w.k * BAY * S + 8, w.f * FLOOR * S + (w.f === 0 ? 4 : 9), BAY * S - 16, FLOOR * S - (w.f === 0 ? 12 : 20),
            { roughness: handQ, bowing: bowQ, seed: seedOf(b.id, w.k * 9 + w.f, 5), fill: '#000', fillStyle: 'solid', stroke: 'none' });
          const wp = new Path2D();
          trace(wp, w.d, fxz, 2);
          g.globalAlpha = 0.75 * fade * clamp01(age * 10) * clamp01((4 - age) / 1.5);
          g.fillStyle = pal.line;
          g.fill(wp);
        }
        // Kick hatching.
        const ha = T - b.hatchT;
        if (ha < 3) {
          if (!b.hatch || b.hatch.ang !== b.hatchAng) {
            b.hatch = { ang: b.hatchAng, d: this.gen.rectangle(0, 0, (b.z1 - b.z0) * S, b.h * S,
              { roughness: handQ, bowing: bowQ, seed: seedOf(b.id, 77, boil), stroke: 'none', fill: '#000', fillStyle: 'hachure', hachureAngle: b.hatchAng, hachureGap: 7, fillWeight: 1 }) };
          }
          const hp = new Path2D();
          trace(hp, b.hatch.d, fxz, 4);
          // Draws on fast, fades slowly.
          g.globalAlpha = b.hatchA * fade * clamp01(ha * 12) * clamp01((3 - ha) / 2) * 0.8;
          g.strokeStyle = pal.line;
          g.lineWidth = 0.9 * press;
          g.stroke(hp);
        }

        const lp = new Path2D();
        for (const d of b.drw.facade) trace(lp, d, fxz, 1);
        if (frontVis) for (const d of b.drw.front) trace(lp, d, frt, 1);
        g.globalAlpha = 0.95 * fade;
        g.strokeStyle = pal.line;
        g.lineWidth = lw;
        g.stroke(lp);

        // Revision clouds (claps): scalloped rough.path in the facade plane.
        for (const r of b.revs) {
          const age = T - r.t;
          if (!r.d) {
            const x0 = r.k0 * BAY * S - 6, y0 = r.f0 * FLOOR * S - 6;
            const w = r.nk * BAY * S + 12, h = r.nf * FLOOR * S + 12;
            r.d = gen.path(scallop(x0, y0, w, h, 11), { roughness: Math.min(handQ, 0.6), bowing: 0.3, seed: seedOf(b.id, r.n, boil) });
            r.tri = gen.polygon([[x0 + w + 6, y0 + h + 4], [x0 + w + 30, y0 + h + 4], [x0 + w + 18, y0 + h + 24]],
              { roughness: Math.min(handQ, 1), seed: seedOf(b.id, r.n, 2) });
            r.tag = [x0 + w + 18, y0 + h + 10];
          }
          if (age > 6) continue;
          const rp = new Path2D();
          trace(rp, r.d, fxz, 1);
          trace(rp, r.tri, fxz, 1);
          g.globalAlpha = fade * clamp01(age * 5) * clamp01((6 - age) / 2);
          g.strokeStyle = pal.red;
          g.lineWidth = 1.6 * press;
          g.stroke(rp);
          fxz(r.tag[0], r.tag[1], TMP);
          const zc = Math.max(NEAR, b.z0 + r.tag[0] / S - cam);
          const px = clamp(F / zc * 0.5, 6, 28);
          if (px > 6.5) {
            g.fillStyle = pal.red;
            g.font = '700 ' + px.toFixed(1) + 'px "Space Mono", monospace';
            g.textAlign = 'center';
            g.textBaseline = 'middle';
            g.fillText(String(r.n), TMP[0], TMP[1]);
          }
        }
      }

      g.strokeStyle = pal.line;
      g.globalAlpha = 0.8;
      g.lineWidth = lw * 0.9;
      g.stroke(gp);

      // ---- lamp posts, on the kerb, every 15 m on both sides
      if (!this.lamps || this.lamps.key !== key) {
        const o = (n) => ({ roughness: handQ, bowing: bowQ, seed: seedOf(8, n, boil) });
        this.lamps = { key, post: [], arm: [], head: [] };
        for (let k = 0; k < 8; k++) {
          this.lamps.post.push(gen.line(0, 0, 0, 55, o(k)));
          this.lamps.arm.push(gen.line(0, 55, -16, 58, o(20 + k)));
          this.lamps.head.push(gen.ellipse(-17, 56, 9, 5, o(40 + k)));
        }
      }
      const lp2 = new Path2D();
      const l0 = Math.ceil((cam + 2) / 15);
      for (let k = 12; k >= 0; k--) {
        const z = (l0 + k) * 15;
        for (const side of [-1, 1]) {
          const i = (((l0 + k) * 2 + (side > 0 ? 1 : 0)) % 8 + 8) % 8;
          // The lamp is drawn in the vertical plane across the street at z,
          // its arm reaching over the road.
          const m = (u, v, out) => proj(side * (KERB + 0.5 + u / S), v / S, z, out);
          trace(lp2, this.lamps.post[i], m, 1);
          trace(lp2, this.lamps.arm[i], m, 1);
        }
      }
      g.globalAlpha = 0.9;
      g.strokeStyle = pal.line;
      g.lineWidth = lw;
      g.stroke(lp2);

      // ---- the sheet: border and title block, fixed to the paper
      this.drawSheet(g, gen, W, H, pal, handQ, bowQ, boil, press);
      g.restore();
    },

    drawSheet(g, gen, W, H, pal, hand, bow, boil, press) {
      const key = W + '|' + hand + '|' + bow + '|' + boil;
      if (!this.sheet || this.sheet.key !== key) {
        const o = (n) => ({ roughness: Math.min(hand, 1.5), bowing: Math.min(bow, 2), seed: seedOf(9, n, boil) });
        const m = 14;
        const tw = 250, th = 64, tx = W - m - tw, ty = H - m - th;
        const lines = [
          gen.rectangle(m, m, W - 2 * m, H - 2 * m, o(1)),
          gen.rectangle(tx, ty, tw, th, o(2)),
          gen.line(tx, ty + 24, tx + tw, ty + 24, o(3)),
          gen.line(tx + 160, ty + 24, tx + 160, ty + th, o(4)),
        ];
        const p2 = new Path2D();
        for (const d of lines) trace(p2, d, ident, 1);
        this.sheet = { key, path: p2, tx, ty, tw, th };
      }
      const s = this.sheet;
      g.globalAlpha = 0.85;
      g.strokeStyle = pal.line;
      g.lineWidth = 1.2 * press;
      g.stroke(s.path);
      g.fillStyle = pal.line;
      g.textAlign = 'left';
      g.textBaseline = 'middle';
      g.font = '700 12px "Space Mono", monospace';
      g.fillText('STREET STUDY · PERSPECTIVE', s.tx + 10, s.ty + 13);
      g.font = '10px "Space Mono", monospace';
      g.globalAlpha = 0.7;
      g.fillText('ONE-POINT · EYE 1.6 M', s.tx + 10, s.ty + 36);
      g.fillText('SCALE NTS', s.tx + 10, s.ty + 51);
      g.fillText('SHEET', s.tx + 170, s.ty + 36);
      g.font = '700 14px "Space Mono", monospace';
      g.fillText('A-' + String(3 + (this.rev % 7)).padStart(2, '0'), s.tx + 170, s.ty + 52);
    },

    // Blueprint mottle and tooth: low-res blotches scaled up, plus grain.
    paperTexture(g, W, H, pal) {
      if (!this.texture || this.texture.pal !== pal) {
        const c = document.createElement('canvas');
        c.width = 192; c.height = 192;
        const t = c.getContext('2d');
        const rng = mulberry(31337);
        for (let k = 0; k < 40; k++) {
          const x = rng() * 192, y = rng() * 192, r = 10 + rng() * 40;
          const gr = t.createRadialGradient(x, y, 0, x, y, r);
          gr.addColorStop(0, pal.blot);
          gr.addColorStop(1, 'rgba(0,0,0,0)');
          t.globalAlpha = 0.25 + 0.3 * rng();
          t.fillStyle = gr;
          for (const ox of [-192, 0, 192]) for (const oy of [-192, 0, 192]) { t.save(); t.translate(ox, oy); t.fillRect(x - r, y - r, 2 * r, 2 * r); t.restore(); }
        }
        const img = t.getImageData(0, 0, 192, 192);
        for (let i = 0; i < img.data.length; i += 4) {
          const n = (rng() - 0.5) * 14;
          img.data[i] += n; img.data[i + 1] += n; img.data[i + 2] += n;
        }
        t.putImageData(img, 0, 0);
        this.texture = { pal, pat: g.createPattern(c, 'repeat') };
      }
      g.save();
      g.globalAlpha = 0.6;
      g.fillStyle = this.texture.pat;
      g.fillRect(0, 0, W, H);
      g.restore();
    },
  });

  // SVG path data for a revision cloud: a run of outward arcs round a
  // rectangle, clockwise.
  function scallop(x, y, w, h, step) {
    const pts = [];
    const edge = (x0, y0, x1, y1) => {
      const n = Math.max(1, Math.round(Math.hypot(x1 - x0, y1 - y0) / step));
      for (let i = 0; i < n; i++) pts.push([x0 + (x1 - x0) * i / n, y0 + (y1 - y0) * i / n]);
    };
    edge(x, y, x + w, y); edge(x + w, y, x + w, y + h); edge(x + w, y + h, x, y + h); edge(x, y + h, x, y);
    let d = 'M' + pts[0][0].toFixed(1) + ' ' + pts[0][1].toFixed(1);
    for (let i = 1; i <= pts.length; i++) {
      const q = pts[i % pts.length];
      d += ' A' + (step * 0.6).toFixed(1) + ' ' + (step * 0.6).toFixed(1) + ' 0 0 0 ' + q[0].toFixed(1) + ' ' + q[1].toFixed(1);
    }
    return d;
  }
})();
